---
- name: Install Apache
  hosts: role_apache
  become: true

  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
        update_cache: false

    - name: Start Apache
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true
        
- name: Install Tomcat
  hosts: role_tomcat
  become: true
  gather_facts: false

  tasks:
    - name: Install Java
      ansible.builtin.apt:
        name: openjdk-17-jdk
        state: present
        update_cache: false

    - name: Install Tomcat
      ansible.builtin.apt:
        name: tomcat10
        state: present
        update_cache: false

    - name: Start Tomcat
      ansible.builtin.service:
        name: tomcat10
        state: started
        enabled: true



